name: CI

on:
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4  # pin til commit-SHA senere

      - name: Set up JDK 21
        uses: actions/setup-java@v4  # pin til commit-SHA senere
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      # Brug wrapperen, så Maven-versionen er konsistent
      - name: Build & Test (Maven)
        run: ./mvnw -B -DskipITs verify
